[terminal.shell]
  program = 'ubuntu'

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window.padding]
x = 10
y = 5

[general]

live_config_reload = true
import = ["colors/rootloops.toml"]