[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window.padding]
x = 10
y = 5

[window]
opacity = 0.95
decorations = "None"

[general]

live_config_reload = true
import = ["colors/catppuccin-mocha.toml"]
